chore(performance): use parallel github actions steps

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -43,17 +43,6 @@ env:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  lint:
-    runs-on: ubuntu-26.04
-    continue-on-error: false
-    steps:
-      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
-        with:
-          fetch-depth: 0 # we need tags for dynamic versioning
-          show-progress: false
-      - name: Run prek hooks (lint)
-        uses: ./.github/actions/prek
-
   package:
     runs-on: ubuntu-26.04
     continue-on-error: false
@@ -73,8 +62,6 @@ jobs:
 
   build:
     name: ${{ matrix.name }}
-    needs:
-      - lint
 
     environment:
       name: ci
@@ -129,14 +116,6 @@ jobs:
             # in order to enable the caching
             continue-on-error: true
 
-          - name: test (linux-wdio)
-            id: test-linux-wdio
-            task-name: wdio
-            os: ubuntu-26.04
-            env:
-              SKIP_PODMAN: 1
-              SKIP_DOCKER: 1
-
           - name: test (wsl)
             id: test-wsl
             task-name: test
@@ -151,6 +130,57 @@ jobs:
           fetch-depth: 0 # we need tags for dynamic versioning
           fetch-tags: true # needed for dynamic versioning
           show-progress: false
+
+      # # We want to lint as early as possible, even before running setup action
+      # # and stop if it fails to save compute resources.
+      # - name: Install uv (cache)
+      #   if: ${{ runner.os == 'Linux' }}
+      #   uses: astral-sh/setup-uv@v8.2.0
+
+      # # needed by our prek systems hooks like biome
+      # - name: Install node (cache)
+      #   if: ${{ runner.os == 'Linux' }}
+      #   uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
+      #   with:
+      #     node-version: "24"
+
+      # - name: Install pnpm # needs node 24
+      #   if: ${{ runner.os == 'Linux' }}
+      #   uses: pnpm/action-setup@v6
+      #   with:
+      #     cache: true
+      #     run_install: |
+      #       - recursive: true
+      #         args: [--frozen-lockfile]
+
+      # - name: Debug
+      #   if: ${{ runner.os == 'Linux' }}
+      #   shell: bash
+      #   run: |
+      #     which -a pnpm
+      #     pnpm --version
+
+      # - name: Enable caching for prek
+      #   if: ${{ runner.os == 'Linux' }}
+      #   uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
+      #   with:
+      #     path: ~/.cache/prek/
+      #     key: prek-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
+
+      # - name: Run prek
+      #   if: ${{ runner.os == 'Linux' }}
+      #   uses: j178/prek-action@v2
+      #   # ideally prek should run in under 30s, but we keep a hard limit of 3
+      #   # minutes to count for slower hooks and uncached data. If a hook is
+      #   # slower, even occasionally it should be moved outside and included in
+      #   # another build step, like 'build' or 'package'.
+      #   # timeout-minutes: 3
+      #   with:
+      #     # show-verbose-logs: true
+      #     # we want to run in verbose to report speed of each hook
+      #     extra-args: "--all-files -v"
+      #     install-only: false
+      #     prek-version: ">=0.3.8"
 
       - name: Run setup steps (composite action)
         uses: ./.github/actions/setup
@@ -275,6 +305,7 @@ jobs:
 
       # Workaround for: https://github.com/actions/runner/issues/1864
       - name: Ensure HOME is defined
+        if: runner.os != 'Windows'
         run: |
           set -euxo pipefail
           if [ -z "${HOME:-}" ]; then
@@ -300,16 +331,33 @@ jobs:
             exit 98
           }
 
+      - parallel:
+          - name: task lint
+            if: runner.os == 'Linux'
+            id: lint
+            run: task lint && task lint --status
+
+          - name: task build / package
+            # Warning: ensure that conditional templates have a negative condition
+            # expanding to an empty string because otherwise it will fail the command
+            # with exit code 1 even if the command effectively succeeded!
+            run: |
+              task build -v -x
+              task build -v --status
+              ${{ runner.os != 'Windows' && 'task package -v' || '' }}
+              ${{ runner.os != 'Windows' && 'task package -v --status' || ''}}
+
+          - name: task docs
+            id: docs
+            shell: bash
+            # timeout-minutes: 2
+            run: task docs && task docs --status
+
       - name: task setup
         # starting podman machine can randomly get stuck on macos
         timeout-minutes: 25
         run: task setup && task setup --status
         id: setup
-
-      - name: task build
-        id: build
-        run: |
-          task build && task build --status
 
       ## uncomment to debug on GHA runner
       # - name: Setup tmate session
@@ -325,45 +373,36 @@ jobs:
           EOT
           podman info
 
-      - name: task package
-        if: ${{ matrix.task-name != 'wdio' && runner.os != 'Windows' }}
-        id: package
-        run: |
-          task package -v ${{ matrix.env.TASKFILE_ARGS }} && task package -v ${{ matrix.env.TASKFILE_ARGS }} --status
+      - parallel:
+          - name: task unit (ext, vue, als, mcp)
+            id: unit
+            if: ${{ !cancelled() && contains(matrix.name, 'test') }}
+            run: |
+              task unit ${{ matrix.env.TASKFILE_ARGS }} && task unit ${{ matrix.env.TASKFILE_ARGS }} --status
 
-      - name: save ready_to_test=true
-        id: ready_to_test
-        if: ${{ contains(matrix.name, 'test') && success() }}
-        run: echo "ready_to_test=true" >> "$GITHUB_OUTPUT"
+          - name: task e2e (vscode-test)
+            id: e2e
+            # https://github.com/ansible/vscode-ansible/issues/1451
+            if: ${{ !cancelled() && contains(matrix.name, 'test') }}
+            run: |
+              set -e
+              task build 2>out/log/build-before.txt
+              task e2e ${{ matrix.env.TASKFILE_ARGS }}
+              task build 2>out/log/build-after.txt
+              task build --status --verbose
+            # Add these once e2e is fixed:
+            #  || { task flush && task e2e ${{ matrix.env.TASKFILE_ARGS }}; }
+            #  task e2e ${{ matrix.env.TASKFILE_ARGS }} --status
 
-      - name: task ${{ matrix.task-name }}
-        if: "${{ !contains(matrix.name, 'test') && !contains(matrix.name, 'wdio') && steps.ready_to_test.outputs.ready_to_test == 'true' }}"
-        run: task ${{ matrix.task-name }} ${{ matrix.env.TASKFILE_ARGS }} && task ${{ matrix.task-name }} ${{ matrix.env.TASKFILE_ARGS }} --status
+          - name: task wdio (VS Code UI)
+            id: wdio
+            if: ${{ runner.os != 'Windows' }}
+            run: task wdio && task wdio --status && task build --status
+            timeout-minutes: 30
 
-      - name: task unit (ext, vue, als, mcp)
-        if: contains(matrix.name, 'test') && matrix.task-name != 'wdio' && steps.ready_to_test.outputs.ready_to_test == 'true'
-        run: |
-          task unit ${{ matrix.env.TASKFILE_ARGS }} && task unit ${{ matrix.env.TASKFILE_ARGS }} --status
-
-      - name: task e2e (vscode-test)
-        # https://github.com/ansible/vscode-ansible/issues/1451
-        if: ${{ !cancelled() && contains(matrix.name, 'test') && matrix.task-name != 'wdio' && steps.ready_to_test.outputs.ready_to_test == 'true' }}
-        run: |
-          set -e
-          task build 2>out/log/build-before.txt
-          task e2e ${{ matrix.env.TASKFILE_ARGS }}
-          task build 2>out/log/build-after.txt
-          task build --status --verbose
-        # Add these once e2e is fixed:
-        #  || { task flush && task e2e ${{ matrix.env.TASKFILE_ARGS }}; }
-        #  task e2e ${{ matrix.env.TASKFILE_ARGS }} --status
-
-      - name: task wdio (VS Code UI)
-        if: ${{ matrix.task-name == 'wdio' && steps.ready_to_test.outputs.ready_to_test == 'true' }}
-        run: |
-          task wdio
-          task build --status
-        timeout-minutes: 30
+      - name: task coverage
+        if: ${{ runner.os != 'Windows' }}
+        run: task coverage
 
       - name: task finish
         run: task finish
@@ -407,7 +446,7 @@ jobs:
         if: ${{ !cancelled() && (runner.os != 'Windows' || contains(matrix.name, 'wsl')) }}
         uses: ansible/actions/upload-artifact@main
         with:
-          name: logs-${{ matrix.name }}-${{ matrix.id }}-${{ github.run_attempt }}.zip
+          name: logs-${{ matrix.id }}-${{ matrix.os }}-${{ github.run_attempt }}.zip
           path: |
             out/als
             out/coverage
@@ -458,7 +497,7 @@ jobs:
 
   mcp-server-image:
     runs-on: ubuntu-26.04
-    needs: [package, lint]
+    needs: [package]
     permissions:
       contents: read
       packages: write
@@ -630,7 +669,7 @@ jobs:
           files: "out/*.vsix"
 
       - run: |
-          pnpm install -y --frozen-lockfile
+          pnpm install -y --frozen-lockfile --reporter append-only
           ls -la out/*.vsix
 
       - name: Publish extension to marketplaces
