chore: use macos-15 builder

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -89,7 +89,7 @@ jobs:
 
           - name: test (macos)
             task-name: test
-            os: macos-13-large
+            os: macos-15-large
             env:
               SKIP_PODMAN: 1
               SKIP_DOCKER: 1
@@ -228,8 +228,8 @@ jobs:
             exit 99
           }
           test "$(mise exec -- which python3)" = "${HOME}/.local/share/virtualenvs/vsa/bin/python3" || {
-            echo "::warning::python3 mismatch"
-            # exit 98
+            echo "::warning::python3 not found at expected location $(mise exec -- which python3)"
+            exit 98
           }
           # Ensure NODE_OPTIONS config on CI is identical with the one in .env
           [[ "${NODE_OPTIONS:-}" == "$(mise exec -- printenv NODE_OPTIONS)" ]] || { echo "NODE_OPTIONS mismatch between .env and ci.yaml"; exit 97; }
